// Code generated by templ@v0.2.334 DO NOT EDIT.

package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"acb/db-interface/sheets"
	"strconv"
)

func fkeySelect(index int, sheet sheets.Sheet, fkeys map[string]map[int64]sheets.ForeignKey, selected int64) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<div class=\"select fkey-select\"><select name=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString("fkey-" + strconv.Itoa(index)))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" hx-post=\"/modal\"><option value=\"\">")
		if err != nil {
			return err
		}
		var_2 := `None`
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</option>")
		if err != nil {
			return err
		}
		for _, tableName := range sheet.TableNames {
			for oid, fkey := range fkeys[tableName] {
				_, err = templBuffer.WriteString("<option value=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(strconv.FormatInt(oid, 10)))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\"")
				if err != nil {
					return err
				}
				if oid == selected {
					_, err = templBuffer.WriteString(" selected")
					if err != nil {
						return err
					}
				}
				_, err = templBuffer.WriteString(">")
				if err != nil {
					return err
				}
				var var_3 string = fkey.ToString()
				_, err = templBuffer.WriteString(templ.EscapeString(var_3))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</option>")
				if err != nil {
					return err
				}
			}
		}
		_, err = templBuffer.WriteString("</select></div>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}

func modal(sheet sheets.Sheet, tableNames []string, fkeys map[string]map[int64]sheets.ForeignKey, addJoin bool) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_4 := templ.GetChildren(ctx)
		if var_4 == nil {
			var_4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<div id=\"modal\" class=\"modal is-active\" hx-target=\"#modal\"><div class=\"modal-content box\"><div id=\"table-fkey-config\" hx-include=\"select,[name=sheet_id]\"><label>")
		if err != nil {
			return err
		}
		var_5 := `Tables`
		_, err = templBuffer.WriteString(var_5)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</label><div class=\"dropdown-list\"><div class=\"select table-select\"><select name=\"table_name\" hx-post=\"/modal\"><option value=\"\"></option>")
		if err != nil {
			return err
		}
		for _, tableName := range tableNames {
			_, err = templBuffer.WriteString("<option value=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(tableName))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\"")
			if err != nil {
				return err
			}
			if tableName == sheet.TableFullName() {
				_, err = templBuffer.WriteString(" selected")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString(">")
			if err != nil {
				return err
			}
			var var_6 string = tableName
			_, err = templBuffer.WriteString(templ.EscapeString(var_6))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</option>")
			if err != nil {
				return err
			}
		}
		_, err = templBuffer.WriteString("</select></div>")
		if err != nil {
			return err
		}
		for index, oid := range sheet.JoinOids {
			err = fkeySelect(index, sheet, fkeys, oid).Render(ctx, templBuffer)
			if err != nil {
				return err
			}
		}
		if addJoin {
			err = fkeySelect(len(sheet.JoinOids), sheet, fkeys, 0).Render(ctx, templBuffer)
			if err != nil {
				return err
			}
		}
		_, err = templBuffer.WriteString("<button hx-post=\"/modal\" name=\"add_join\" class=\"button is-primary\">")
		if err != nil {
			return err
		}
		var_7 := `+ Join`
		_, err = templBuffer.WriteString(var_7)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</button></div></div><div class=\"flex full-width mt center\"><a href=\"")
		if err != nil {
			return err
		}
		var var_8 templ.SafeURL = templ.SafeURL("?sheet_id=" + strconv.Itoa(sheet.Id))
		_, err = templBuffer.WriteString(templ.EscapeString(string(var_8)))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" class=\"button is-primary\">")
		if err != nil {
			return err
		}
		var_9 := `Ok`
		_, err = templBuffer.WriteString(var_9)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</a></div></div><button class=\"modal-close\"></button><input name=\"sheet_id\" type=\"hidden\" value=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(strconv.Itoa(sheet.Id)))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\"></div>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
