// Code generated by templ@v0.2.334 DO NOT EDIT.

package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"acb/db-interface/sheets"
	"fmt"
	"strconv"
)

func colName(name string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<span hx-post=\"/set-column-prefs\" hx-vals=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("js:{col_name:\"%s\",hide:shiftPressed}", name)))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\">")
		if err != nil {
			return err
		}
		var var_2 string = name
		_, err = templBuffer.WriteString(templ.EscapeString(var_2))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</span>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}

func extraColName(i int, name string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_3 := templ.GetChildren(ctx)
		if var_3 == nil {
			var_3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<input name=\"col_name\" hx-vals=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("{\"col_index\":%d}", i)))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" value=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(name))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" hx-post=\"/rename-column\" hx-swap=\"none\">")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}

func tableCell(tableName string, col sheets.Column, row int, cell sheets.Cell, err error) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_4 := templ.GetChildren(ctx)
		if var_4 == nil {
			var_4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if col.IsPrimaryKey {
			_, err = templBuffer.WriteString("<div hx-get=\"/new-row\" hx-trigger=\"click\" hx-vals=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("{\"table_name\":\"%s\"}", tableName)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" hx-include=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("[name=sheet_id],tr[data-row=\"%d\"] [data-table=\"%s\"][name^=pk-]", row, tableName)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" hx-target=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("tr[data-row=\"%d\"]", row)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" hx-swap=\"afterend\">")
			if err != nil {
				return err
			}
			var var_5 string = cell.Value
			_, err = templBuffer.WriteString(templ.EscapeString(var_5))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</div>")
			if err != nil {
				return err
			}
		} else {
			var var_6 = []any{templ.KV("is-danger", err != nil)}
			err = templ.RenderCSSItems(ctx, templBuffer, var_6...)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("<input name=\"value\" hx-post=\"/set-cell\" hx-target=\"this\" hx-swap=\"outerHTML\" hx-vals=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("{\"table_name\":\"%s\",\"col_name\":\"%s\",\"row\":%d}", tableName, col.Name, row)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" hx-include=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("[name=sheet_id],tr[data-row=\"%d\"] [data-table=\"%s\"][name^=pk-]", row, tableName)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" value=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(cell.Value))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" size=\"1\" class=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(templ.CSSClasses(var_6).String()))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\">")
			if err != nil {
				return err
			}
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}

func extraCell(i, j int, cell sheets.SheetCell) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_7 := templ.GetChildren(ctx)
		if var_7 == nil {
			var_7 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var var_8 = []any{"extra-cell", templ.KV("is-null", !cell.NotNull)}
		err = templ.RenderCSSItems(ctx, templBuffer, var_8...)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<td class=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(templ.CSSClasses(var_8).String()))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\"><input name=\"formula\" class=\"extra-cell-formula hide\" value=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(cell.Formula))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" hx-post=\"/set-cell\" hx-vals=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("{\"i\":%d,\"j\":%d}", i, j)))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" hx-target=\"closest td\" hx-swap=\"outerHTML\"><span class=\"extra-cell-value\">")
		if err != nil {
			return err
		}
		var var_9 string = cell.Value
		_, err = templBuffer.WriteString(templ.EscapeString(var_9))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</span></td>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}

func newRow(tableNames []string, tableIndex int, cols [][]sheets.Column, numCols int, cells []sheets.Cell, rowIndex int) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_10 := templ.GetChildren(ctx)
		if var_10 == nil {
			var_10 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<tr id=\"new-row\">")
		if err != nil {
			return err
		}
		for i, tcols := range cols {
			for j, col := range tcols {
				var var_11 = []any{templ.KV("is-null", len(cells) > 0 && !cells[j].NotNull)}
				err = templ.RenderCSSItems(ctx, templBuffer, var_11...)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("<td style=\"border-bottom: none\" class=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(templ.CSSClasses(var_11).String()))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\">")
				if err != nil {
					return err
				}
				if tableIndex == i && len(cells) > 0 {
					_, err = templBuffer.WriteString("<span>")
					if err != nil {
						return err
					}
					var var_12 string = cells[j].Value
					_, err = templBuffer.WriteString(templ.EscapeString(var_12))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</span>")
					if err != nil {
						return err
					}
				} else {
					_, err = templBuffer.WriteString("<input name=\"")
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString(templ.EscapeString("column-" + tableNames[i] + " " + col.Name))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("\">")
					if err != nil {
						return err
					}
				}
				_, err = templBuffer.WriteString("</td>")
				if err != nil {
					return err
				}
			}
		}
		_, err = templBuffer.WriteString("</tr><tr id=\"new-row-err-container\"><td colspan=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("%d", numCols)))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" style=\"border-top: none\"><div class=\"flex center\"><button hx-post=\"/add-row\" hx-include=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("[name=sheet_id],#new-row,tr[data-row=\"%d\"] [data-table=\"%s\"][name^=pk-]", rowIndex, tableNames[tableIndex])))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" hx-include=\"#new-row\" hx-target-400=\"#new-row-err\" class=\"button is-light maround\">")
		if err != nil {
			return err
		}
		var_13 := `Add`
		_, err = templBuffer.WriteString(var_13)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</button><span id=\"new-row-err\" class=\"has-text-danger\"></span></div></td></tr>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}

func sheetTable(sheet sheets.Sheet, tableNames []string, cols [][]sheets.Column, cells [][][]sheets.Cell, numCols int) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_14 := templ.GetChildren(ctx)
		if var_14 == nil {
			var_14 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<thead><tr>")
		if err != nil {
			return err
		}
		for i, tableName := range tableNames {
			_, err = templBuffer.WriteString("<th colspan=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(strconv.Itoa(len(cols[i]))))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\">")
			if err != nil {
				return err
			}
			var var_15 string = tableName
			_, err = templBuffer.WriteString(templ.EscapeString(var_15))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</th>")
			if err != nil {
				return err
			}
		}
		_, err = templBuffer.WriteString("</tr><tr id=\"header-row\">")
		if err != nil {
			return err
		}
		for _, tcols := range cols {
			for _, col := range tcols {
				var var_16 = []any{templ.KV("is-pkey", col.IsPrimaryKey)}
				err = templ.RenderCSSItems(ctx, templBuffer, var_16...)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("<th class=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(templ.CSSClasses(var_16).String()))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\">")
				if err != nil {
					return err
				}
				err = colName(col.Name).Render(ctx, templBuffer)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</th>")
				if err != nil {
					return err
				}
			}
		}
		for i, col := range sheet.ExtraCols {
			_, err = templBuffer.WriteString("<th>")
			if err != nil {
				return err
			}
			err = extraColName(i, col.Name).Render(ctx, templBuffer)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</th>")
			if err != nil {
				return err
			}
		}
		_, err = templBuffer.WriteString("</tr></thead><tbody>")
		if err != nil {
			return err
		}
		for j := 0; j < sheet.RowCount; j++ {
			_, err = templBuffer.WriteString("<tr class=\"body-row\" data-row=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(strconv.Itoa(j)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\">")
			if err != nil {
				return err
			}
			for i, tableCols := range cells {
				for k, cells := range tableCols {
					var var_17 = []any{templ.KV("is-null", !cells[j].NotNull)}
					err = templ.RenderCSSItems(ctx, templBuffer, var_17...)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("<td class=\"")
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString(templ.EscapeString(templ.CSSClasses(var_17).String()))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("\"><span class=\"width-control\">")
					if err != nil {
						return err
					}
					var var_18 string = cells[j].Value
					_, err = templBuffer.WriteString(templ.EscapeString(var_18))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</span>")
					if err != nil {
						return err
					}
					err = tableCell(tableNames[i], cols[i][k], j, cells[j], nil).Render(ctx, templBuffer)
					if err != nil {
						return err
					}
					if cols[i][k].IsPrimaryKey && cells[j].NotNull {
						_, err = templBuffer.WriteString("<input name=\"")
						if err != nil {
							return err
						}
						_, err = templBuffer.WriteString(templ.EscapeString("pk-" + cols[i][k].Name))
						if err != nil {
							return err
						}
						_, err = templBuffer.WriteString("\" data-table=\"")
						if err != nil {
							return err
						}
						_, err = templBuffer.WriteString(templ.EscapeString(tableNames[i]))
						if err != nil {
							return err
						}
						_, err = templBuffer.WriteString("\" value=\"")
						if err != nil {
							return err
						}
						_, err = templBuffer.WriteString(templ.EscapeString(cells[j].Value))
						if err != nil {
							return err
						}
						_, err = templBuffer.WriteString("\" type=\"hidden\">")
						if err != nil {
							return err
						}
					}
					_, err = templBuffer.WriteString("</td>")
					if err != nil {
						return err
					}
				}
			}
			for i, extraCol := range sheet.ExtraCols {
				err = extraCell(i, j, extraCol.Cells[j]).Render(ctx, templBuffer)
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString("</tr>")
			if err != nil {
				return err
			}
		}
		_, err = templBuffer.WriteString("</tbody>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
